class Admin::TrackingController < ApplicationController
  resource_controller

  def generate
    # Retrieve shipment object
    begin
      tmp_shipment = Shipment.find(params[:id])
    rescue
      tmp_shipment = nil
    end
    
    unless tmp_shipment.nil?
      case tmp_shipment.shipping_method.shipping_type.identifier
        when "tnt" then tracking = TrackingTnt.new(tmp_shipment)
        when "chronopost" then tracking = TrackingChronopost.new(tmp_shipment)
      end

      unless tracking.nil?
        # Create Object File and write String Generated by TrackingEngine
        f = File.open("/tmp/tracking/#{tracking.named_file}", 'w')
        f.write tracking.file
        f.close

        # Send the file
        send_file("#{f.path}", :type => "text/plain")
      end
    end
  end
end
