class TrackingChronopost

  attr_reader :file, :named_file

  @@xml_file_path_pattern = "#{SPREE_ROOT}/vendor/extensions/spree_tracking/config/tracking_chronopost_pattern.xml"

  def initialize(shipment)
    # Instanciate variable
    @named_file = "caisse.txt"

    # Define Separator
    separator = ';'

    # Define Hash to perform
    fields_hash = define_hash_fields(shipment)

    # Retrieve File Generated by Tracking Engine
    @file = TrackingEngine.new(@@xml_file_path_pattern, :fields_hash => fields_hash, :separator => separator).file
  end

  #########################
  # GENERAL FIELDS GETTER #
  #########################

  # Define fields for a shipment
  # shipment : Represent the shipment object
  def define_hash_fields(shipment)
    # Instanciate Hash
    fields = Hash.new

    ##################
    # EDIT THIS HASH #
    ##################

    # Initialize fields Hash
    # Each key of Fields Hash MUST match XML Fields Value
    # Link Each Key Field with a function to retrieve value from ActiveRecord
    fields = {
      "order_id" => "#{retrieve_order_id(shipment)}",
      'last_name_first_name' => "#{retrieve_last_name_first_name(shipment)}",
      "address_line1" => "#{retrieve_address_line1(shipment)}",
      "address_line2" => "#{retrieve_address_line2(shipment)}",
      'zipcode' => "#{retrieve_zipcode(shipment)}",
      "city" => "#{retrieve_city(shipment).to_s}",
      "shipment_weight" => "#{retrieve_shipment_weight(shipment)}",
      'phone' => "#{retrieve_phone(shipment)}",
      'country_code' => "#{retrieve_country_code(shipment)}",
      'amount_refund' => "#{retrieve_amount_refund(shipment)}",
      'email' => "#{retrieve_email(shipment)}",
      'empty' => ""
    }

    ##############
    #  END EDIT  #
    ##############

    fields
  end

  #################
  # FIELDS GETTER #
  #################

  # Retrieve the shipment order id
  def retrieve_order_id(shipment)
    shipment.order.id
  end

  # Concate Last_name and First_name
  def retrieve_last_name_first_name(shipment)
    # Instanciate variable
    result = ''

    # Retrieve variable lastname and firstname
    lastname = shipment.address.lastname
    firstname = shipment.address.firstname

    # Concate value
    result += lastname unless lastname.nil?
    result += ' ' unless lastname.nil?
    result += firstname unless firstname.nil?

    # Return value
    result
  end

  # Retrieve User Address
  def retrieve_address_line1(shipment)
    # Instanciate variable
    result = ''

    # Retrieve variable lastname and firstname
    address_line1 = shipment.address.address1

    # Concate value
    result += address_line1 unless address_line1.nil?

    # Return value
    result
  end
  
  # Retrieve User Address
  def retrieve_address_line2(shipment)
    # Instanciate variable
    result = ''

    # Retrieve variable lastname and firstname
    address_line2 = shipment.address.address2

    # Concate value
    result += address_line2 unless address_line2.nil?

    # Return value
    result
  end

  # Retrieve Zipcode
  def retrieve_zipcode(shipment)
    shipment.address.zipcode
  end

  # Retrieve Town
  def retrieve_city(shipment)
    shipment.address.city
  end

  # Retrieve country code
  def retrieve_country_code(shipment)
    shipment.address.country.iso
  end

  # Retrieve customer phone number
  def retrieve_phone(shipment)
    shipment.address.phone
  end

  # Retrieve shipement weight
  def retrieve_shipment_weight(shipment)
    # Instanciate weight
    result = ''

    result = shipment.weight unless shipment.weight.empty?

    result
  end

  # Retrieve email
  def retrieve_email(shipment)
    shipment.order.user.email
  end

  # Retrieve amount_refund if it s included for this shipment
  def retrieve_amount_refund(shipment)
    ''
  end
end
